#!/bin/sh
source setup.sh
EXT=ext0

PREV_CFG=step1_GEN_SIM.py
CFG=step2_DIGI_L1_DIGI2RAW_HLT.py
INPUT_DIR=${OUTPUT_ROOT}/step1_GEN_SIM/${EXT}
OUTPUT_DIR=${OUTPUT_ROOT}/step2_DIGI_L1_DIGI2RAW_HLT/${EXT}
submit_pool ${PREV_CFG} ${CFG} ${INPUT_DIR} ${OUTPUT_DIR}
